version: '3.9'

services:
  postgres:
    container_name: fastapi-gen-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - fastapi-gen
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    container_name: fastapi-gen-api
    restart: unless-stopped
    volumes:
      - .:/api
    networks:
      - fastapi-gen
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SECRET: ${SECRET}
    depends_on:
      - postgres

volumes:
  db:
    driver: local

networks:
  fastapi-gen: